name: Frontend Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'
    - name: npm install, lint and test
      id: test
      run: |
        npm install
        npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Build Docker Image and Push to GHCR, Docker Hub, or AWS ECR
      # You may pin to the exact commit or the version.
      # uses: GlueOps/github-actions-build-push-containers@c095833c92eaaea5427d1dbc3e83845abeb5f66c
      uses: GlueOps/github-actions-build-push-containers@v0.3.7
      with:
        registry: ${{ secrets.REGISTRY }}
        image_name: frontend-service
        # Comma-separate list of tags for built image.  Defaults to GlueOps tags
        tags: cicd-example
        # AWS Access Key ID - to be used in conjunction with `aws_secret_access_key`
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        # AWS Secret Access Key - to be used in conjunction with `aws_access_key_id`
        aws_secret_access_key: ${{ secrets.ACCESS_KEY_ID }}
        # AWS IAM Role to assume, when using the GitHub OIDC provider in conjunction with a configured AWS IAM Identity Provider endpoint and instead of access key / secret key pair
        aws_role_to_assume: ${{ secrets.ROLE }}
        # AWS Default Region
        aws_default_region: eu-north-1
        # Version of AWS CLI to use, default is 2.15.30
        aws_cli_version: 2.15.30
          
