name: Frontend Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    environment: production
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'
    - name: npm install, lint and test
      id: test
      run: |
        npm install
        npm run lint
  get-version:
    name: Get Project Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    environment: production
    needs: test
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'
    - name: Get project version
      id: get-version
      run: |
        response="$(npm pkg get version | xargs)"
        
        if [[ $? -eq 0 ]]; then
          echo "version=$response" >> "$GITHUB_OUTPUT"
          echo "$response"
        else
          echo "Error: $response"
          exit 1
        fi
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    needs:
      - test
      - get-version
    steps:
    - name: Build Docker Image and Push to GHCR, Docker Hub, or AWS ECR
      env:
        VERSION: ${{ needs.get-version.outputs.version }}
      uses: GlueOps/github-actions-build-push-containers@v0.3.7
      with:
        registry: ${{ vars.CONTAINER_REGISTRY }}
        image_name: cicd-example-frontend-service
        # Comma-separate list of tags for built image.  Defaults to GlueOps tags
        tags: $VERSION
        # AWS Access Key ID - to be used in conjunction with `aws_secret_access_key`
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS Secret Access Key - to be used in conjunction with `aws_access_key_id`
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        # AWS IAM Role to assume, when using the GitHub OIDC provider in conjunction with a configured AWS IAM Identity Provider endpoint and instead of access key / secret key pair
#        aws_role_to_assume: ${{ secrets.ROLE }}
        # AWS Default Region
        aws_default_region: ${{ vars.AWS_REGION }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs:
      - build
    steps:
      - name: Deploy image to AWS App Runner
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        run: |
          echo "Implement Deploy!"
#          response="$(aws apprunner update-service --service-arn <value> --source-configuration <value>)"
#
#          if [[ $? -eq 0 ]]; then
#            echo "Successfully deployed service"
#          else
#            echo "Error: $response"
#            exit 1
#          fi